name: giziku
description: "Aplikasi yang digunakan untuk menghitung kalori harian yang terintegrasi AI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: any
  firebase_auth: any
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  camera: ^0.11.0
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  google_generative_ai: ^0.4.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  fl_chart: ^0.66.2
  shared_preferences: ^2.5.4
  flutter_timezone: ^3.0.0
  flutter_slidable: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-giziku.png"
  min_sdk_android: 21