// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:474602069857:web:f24a4e98c1582ad4632f20',
    messagingSenderId: '474602069857',
    projectId: 'giziku-app',
    authDomain: 'giziku-app.firebaseapp.com',
    storageBucket: 'giziku-app.firebasestorage.app',
    measurementId: 'G-86W3CRY54D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:474602069857:android:1da2a4574792e533632f20',
    messagingSenderId: '474602069857',
    projectId: 'giziku-app',
    storageBucket: 'giziku-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:474602069857:ios:7891e0b7053f1fec632f20',
    messagingSenderId: '474602069857',
    projectId: 'giziku-app',
    storageBucket: 'giziku-app.firebasestorage.app',
    iosBundleId: 'com.example.giziku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:474602069857:ios:7891e0b7053f1fec632f20',
    messagingSenderId: '474602069857',
    projectId: 'giziku-app',
    storageBucket: 'giziku-app.firebasestorage.app',
    iosBundleId: 'com.example.giziku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:474602069857:web:feb426809189e9b1632f20',
    messagingSenderId: '474602069857',
    projectId: 'giziku-app',
    authDomain: 'giziku-app.firebaseapp.com',
    storageBucket: 'giziku-app.firebasestorage.app',
    measurementId: 'G-5J8LHWZMRF',
  );

}
